version: '3.8'

services:
  # 1. Servicio de Base de Datos
  postgres-db:
    image: postgres:15-alpine
    container_name: glass_distributor_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. Servicio de Interfaz Gráfica (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: glass_distributor_pgadmin
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres-db

# Esto asegura que los datos no se borren si apagas la computadora
volumes:
  pgdata:
    name: glass_distributor_pgdata